/*

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.

Answer: 4613732 */

#include <stdio.h>
#include <math.h>

int
main()
{
	double prvi = 1;
	double drugi = 2;
	double suma = 2;
	double treci = prvi + drugi;

	while (treci < 4.0e6)
	{
		if (fmod (treci, 2) == 0.0d)
		{
			suma += treci;
			printf("%.0f\n", treci);
		}
		prvi = drugi;
		drugi = treci;
		treci = prvi + drugi;
	}
	printf("%.0f", suma);
}